### ISSUE TITLE
Google Tag Manager - Study Spot doesn't have any reporting and tracking

### ISSUE THREAD

**Issue by victoryoung08** [victoryoung08/study-spot#20]
### Summary

Access has already previous been provided.

Can you please confirm if it has been implemented?
GTM requirements
- GA4
- Meta Pixel

### Basic Example

Access has already previous been provided.

Can you please confirm if it has been implemented?
GTM requirements
- GA4
- Meta Pixel

### Drawbacks

Access has already previous been provided.

Can you please confirm if it has been implemented?
GTM requirements
- GA4
- Meta Pixel

**Comment by jomarmontuya** [comment]
@victoryoung08  can you please send me the metapixel tracking code for me to add it
